name: flutapp_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MajorMonoDisplay
      fonts:
        - asset: fonts/MajorMonoDisplay-Regular.ttf
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-VariableFont_wght.ttf
    - family: SourceCodeProItalic
      fonts:
        - asset: fonts/SourceCodePro-Italic-VariableFont_wght.ttf
